//
// LedgerResponseDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LedgerResponseDTO: Codable {

    public var memo: String?
    public var personalSum: Int?
    public var subsidySum: Int?
    public var subsidyAvailable: [SubsidyAvailable]?
    public var total: Int?
    public var ledgerDetailResponseDTOS: [LedgerDetailResponseDTO]?

    public init(memo: String? = nil, personalSum: Int? = nil, subsidySum: Int? = nil, subsidyAvailable: [SubsidyAvailable]? = nil, total: Int? = nil, ledgerDetailResponseDTOS: [LedgerDetailResponseDTO]? = nil) {
        self.memo = memo
        self.personalSum = personalSum
        self.subsidySum = subsidySum
        self.subsidyAvailable = subsidyAvailable
        self.total = total
        self.ledgerDetailResponseDTOS = ledgerDetailResponseDTOS
    }


}
