//
// LedgerRequestDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LedgerRequestDTO: Codable {

    public var date: String?
    public var count: Int?
    public var content: String?
    public var memo: String?
    public var expenditureRequestDTOList: [ExpenditureRequestDTO]?

    public init(date: String? = nil, count: Int? = nil, content: String? = nil, memo: String? = nil, expenditureRequestDTOList: [ExpenditureRequestDTO]? = nil) {
        self.date = date
        self.count = count
        self.content = content
        self.memo = memo
        self.expenditureRequestDTOList = expenditureRequestDTOList
    }


}
