//
// LedgerMemoRequestDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LedgerMemoRequestDTO: Codable {

    public var memo: String?

    public init(memo: String? = nil) {
        self.memo = memo
    }


}
