//
// LedgerDetailResponseDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LedgerDetailResponseDTO: Codable {

    public enum Color: String, Codable { 
        case blue = "BLUE"
        case green = "GREEN"
        case yellow = "YELLOW"
        case red = "RED"
    }
    public var ledgerId: Int64?
    public var expenditureId: Int64?
    public var date: String?
    public var count: Int?
    public var color: Color?
    public var name: String?
    public var content: String?
    public var amount: Int?
    public var memo: String?

    public init(ledgerId: Int64? = nil, expenditureId: Int64? = nil, date: String? = nil, count: Int? = nil, color: Color? = nil, name: String? = nil, content: String? = nil, amount: Int? = nil, memo: String? = nil) {
        self.ledgerId = ledgerId
        self.expenditureId = expenditureId
        self.date = date
        self.count = count
        self.color = color
        self.name = name
        self.content = content
        self.amount = amount
        self.memo = memo
    }


}
