//
// NotificationDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct NotificationDTO: Codable {

    public enum NotificationType: String, Codable { 
        case clap = "CLAP"
        case support = "SUPPORT"
        case reply = "REPLY"
    }
    public var _id: Int64?
    public var targetKey: String?
    public var notificationType: NotificationType?
    public var sender: String?
    public var createdAt: String?
    public var elapsedTime: String?

    public init(_id: Int64? = nil, targetKey: String? = nil, notificationType: NotificationType? = nil, sender: String? = nil, createdAt: String? = nil, elapsedTime: String? = nil) {
        self._id = _id
        self.targetKey = targetKey
        self.notificationType = notificationType
        self.sender = sender
        self.createdAt = createdAt
        self.elapsedTime = elapsedTime
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case targetKey
        case notificationType
        case sender
        case createdAt
        case elapsedTime
    }

}
