//
// NotificationResponseDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct NotificationResponseDTO: Codable {

    public var dto: [NotificationDTO]?
    public var currentPage: Int?
    public var totalPage: Int?
    public var totalElements: Int?

    public init(dto: [NotificationDTO]? = nil, currentPage: Int? = nil, totalPage: Int? = nil, totalElements: Int? = nil) {
        self.dto = dto
        self.currentPage = currentPage
        self.totalPage = totalPage
        self.totalElements = totalElements
    }


}
