//
// NotificationResponseDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

struct NotificationResponseDTO: Codable {
    var dto: [NotificationDTO]?
    var currentPage: Int?
    var totalPage: Int?
    var totalElements: Int?

    init(dto: [NotificationDTO]? = nil, currentPage: Int? = nil, totalPage: Int? = nil, totalElements: Int? = nil) {
        self.dto = dto
        self.currentPage = currentPage
        self.totalPage = totalPage
        self.totalElements = totalElements
    }
    
    
}

