//
// ChallengeParticipantsDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChallengeParticipantsDTO: Codable {

    public var dto: [ChallengeParticipantDTO]?
    public var currentPage: Int?
    public var totalPage: Int?
    public var totalItems: Int?

    public init(dto: [ChallengeParticipantDTO]? = nil, currentPage: Int? = nil, totalPage: Int? = nil, totalItems: Int? = nil) {
        self.dto = dto
        self.currentPage = currentPage
        self.totalPage = totalPage
        self.totalItems = totalItems
    }


}
