////
//// ChallengeDTO.swift
////
//// Generated by swagger-codegen
//// https://github.com/swagger-api/swagger-codegen
////
//
// import Foundation
//
//
//
// public struct ChallengeDTO: Codable {
//
//    public var _id: Int64?
//    public var point: Int?
//    public var image: Any?
//    public var name: String?
//    public var _description: String?
//    public var participants: Int?
//    public var _open: Bool?
//    public var participating: Bool?
//
//    public init(_id: Int64? = nil, point: Int? = nil, image: Any? = nil, name: String? = nil, _description: String? = nil, participants: Int? = nil, _open: Bool? = nil, participating: Bool? = nil) {
//        self._id = _id
//        self.point = point
//        self.image = image
//        self.name = name
//        self._description = _description
//        self.participants = participants
//        self._open = _open
//        self.participating = participating
//    }
//
//    public enum CodingKeys: String, CodingKey {
//        case _id = "id"
//        case point
//        case image
//        case name
//        case _description = "description"
//        case participants
//        case _open = "open"
//        case participating
//    }
//
// }
