//
// ChallengeParticipantDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChallengeParticipantDTO: Codable {

    public var userId: Int64?
    public var nickname: String?
    public var thoughts: String?
    public var supported: Bool?

    public init(userId: Int64? = nil, nickname: String? = nil, thoughts: String? = nil, supported: Bool? = nil) {
        self.userId = userId
        self.nickname = nickname
        self.thoughts = thoughts
        self.supported = supported
    }


}
