//
// ChallengeCreateRequestDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChallengeCreateRequestDTO: Codable {

    public enum ChallengeEmojiType: String, Codable { 
        case red = "RED"
        case orange = "ORANGE"
        case yellow = "YELLOW"
        case green = "GREEN"
        case blue = "BLUE"
        case purple = "PURPLE"
        case black = "BLACK"
    }
    public var challengeEmojiType: ChallengeEmojiType?
    public var name: String?
    public var _description: String?

    public init(challengeEmojiType: ChallengeEmojiType? = nil, name: String? = nil, _description: String? = nil) {
        self.challengeEmojiType = challengeEmojiType
        self.name = name
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case challengeEmojiType
        case name
        case _description = "description"
    }

}
