//
// ChallengeCompleteRequestDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChallengeCompleteRequestDTO: Codable {

    public var thoughts: String?

    public init(thoughts: String? = nil) {
        self.thoughts = thoughts
    }


}
