//
// ChallengeNameRequestDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChallengeNameRequestDTO: Codable {

    public var challengeNickname: String?

    public init(challengeNickname: String? = nil) {
        self.challengeNickname = challengeNickname
    }


}
