//
// ChallengeResponseDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChallengeResponseDTO: Codable {

    public var dtos: [ChallengeDTO]?

    public init(dtos: [ChallengeDTO]? = nil) {
        self.dtos = dtos
    }


}
