//
// MyChallengeTotalDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MyChallengeTotalDTO: Codable {

    public var dtos: [MyChallengeDTO]?

    public init(dtos: [MyChallengeDTO]? = nil) {
        self.dtos = dtos
    }


}
