//
// MyChallengeDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MyChallengeDTO: Codable {

    public var _id: Int64?
    public var name: String?
    public var image: String?
    public var participants: Int?
    public var startDate: String?
    public var firstDate: String?
    public var successDays: [String]?

    public init(_id: Int64? = nil, name: String? = nil, image: String? = nil, participants: Int? = nil, startDate: String? = nil, firstDate: String? = nil, successDays: [String]? = nil) {
        self._id = _id
        self.name = name
        self.image = image
        self.participants = participants
        self.startDate = startDate
        self.firstDate = firstDate
        self.successDays = successDays
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case image
        case participants
        case startDate
        case firstDate
        case successDays
    }

}
