//
// UserSpouseCodeResponseDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserSpouseCodeResponseDTO: Codable {

    public var spouseCode: String?

    public init(spouseCode: String? = nil) {
        self.spouseCode = spouseCode
    }


}
