//
// UserHusbandJoinRequestDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

struct UserHusbandJoinRequestDTO: Codable {
    var spouseCode: String?
    var ssn: String?
    var fcmToken: String?

    public init(spouseCode: String? = nil, ssn: String? = nil, fcmToken: String? = nil) {
        self.spouseCode = spouseCode
        self.ssn = ssn
        self.fcmToken = fcmToken
    }
}
