//
// UserJoinRequestDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

struct UserJoinRequestDTO: Codable {
    var surgeryType: SurgeryType?
    var count: Int?
    var startAt: String?
    var spouseCode: String?
    var ssn: String?
    var fcmToken: String?

    public init(surgeryType: SurgeryType? = nil, count: Int? = nil, startAt: String? = nil, spouseCode: String? = nil, ssn: String? = nil, fcmToken: String? = nil) {
        self.surgeryType = surgeryType
        self.count = count
        self.startAt = startAt
        self.spouseCode = spouseCode
        self.ssn = ssn
        self.fcmToken = fcmToken
    }
}
