//
// HomeRecordResponseDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

struct HomeRecordResponseDTO: Codable {
    enum RecordType: String, Codable {
        case medicine = "MEDICINE"
        case injection = "INJECTION"
        case hospital = "HOSPITAL"
        case etc = "ETC"
    }

    let id: Int64?
    let recordType: RecordType?
    let time: String?
    let name: String?
    let memo: String?
    let todo: Bool?

    init(id: Int64? = nil, recordType: RecordType? = nil, time: String? = nil, name: String? = nil, memo: String? = nil, todo: Bool? = nil) {
        self.id = id
        self.recordType = recordType
        self.time = time
        self.name = name
        self.memo = memo
        self.todo = todo
    }

    enum CodingKeys: String, CodingKey {
        case id = "_id"
        case recordType
        case time
        case name
        case memo
        case todo
    }
}
