//
// MyPageMedicalRecordResponseDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MyPageMedicalRecordResponseDTO: Codable {

    public var myPageRecordResponseDTO: [MyPageRecordResponseDTO]?

    public init(myPageRecordResponseDTO: [MyPageRecordResponseDTO]? = nil) {
        self.myPageRecordResponseDTO = myPageRecordResponseDTO
    }


}
