//
// MyPageMedicalRecordResponseDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

struct MyPageMedicalRecordResponseDTO: Codable {
    var myPageRecordResponseDTO: [MyPageRecordResponseDTO]?

    init(myPageRecordResponseDTO: [MyPageRecordResponseDTO]? = nil) {
        self.myPageRecordResponseDTO = myPageRecordResponseDTO
    }
}

extension MyPageMedicalRecordResponseDTO {}
