//
// MyPageRecordResponseDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct MyPageRecordResponseDTO: Codable {

    public var _id: Int64?
    public var date: String?
    public var startDate: String?
    public var endDate: String?
    public var repeatDays: String?
    public var name: String?
    public var dose: String?

    public init(_id: Int64? = nil, date: String? = nil, startDate: String? = nil, endDate: String? = nil, repeatDays: String? = nil, name: String? = nil, dose: String? = nil) {
        self._id = _id
        self.date = date
        self.startDate = startDate
        self.endDate = endDate
        self.repeatDays = repeatDays
        self.name = name
        self.dose = dose
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case date
        case startDate
        case endDate
        case repeatDays
        case name
        case dose
    }

}
